include:
  - "https://gitlab.com/smartive/open-source/gitlab-ci-templates/raw/master/templates.yml"

stages:
  - test
  - release

.public-docker:
  extends: .base
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_FILE: ./Dockerfile
    DOCKER_TAG: ""
    DOCKER_CONTEXT: "."
    DOCKER_BUILDKIT: "1"
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - docker build --file $DOCKER_FILE -t $DOCKER_TAG $DOCKER_CONTEXT
  after_script:
    - docker push $DOCKER_TAG

test:
  extends: .public-docker
  stage: test
  before_script: []
  after_script: []
  script:
    - docker build --file $DOCKER_FILE --target build $DOCKER_CONTEXT
  except:
    - master
    - tags

release:
  extends: .create-release
  stage: release
  only:
    - master

deploy:
  extends: .public-docker
  stage: release
  variables:
    DOCKER_TAG: "smartive/web-exporter:$CI_COMMIT_TAG"
  only:
    - tags
