include:
  - "https://gitlab.com/smartive/open-source/gitlab-ci-templates/raw/master/templates.yml"

stages:
  - test
  - release

.public-docker:
  extends: .base
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_FILE: ./Dockerfile
    DOCKER_CONTEXT: "."
    DOCKER_BUILDKIT: "1"
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD

test:
  extends: .public-docker
  stage: test
  before_script: []
  script:
    - docker build --file $DOCKER_FILE --target build $DOCKER_CONTEXT
  except:
    - master
    - tags

release:
  extends: .create-release
  stage: release
  only:
    - master

deploy:
  extends: .public-docker
  stage: release
  script:
    - docker build --file $DOCKER_FILE -t smartive/web-exporter:$CI_COMMIT_TAG $DOCKER_CONTEXT
    - docker tag smartive/web-exporter:$CI_COMMIT_TAG smartive/web-exporter:latest
  after_script:
    - docker push smartive/web-exporter:$CI_COMMIT_TAG
    - docker push smartive/web-exporter:latest
  only:
    - tags
